In [1]:
# Loading the Library with the Iris DataSet:
from sklearn.datasets import load_iris
# Loading scikit's Random Forest Classifier Library;
from sklearn.ensemble import RandomForestClassifier
# Loading Pandas:
import pandas as pd
# Loading Numpy:
import numpy as np
# Setting Random Seed:
np.random.seed(0)

In [2]:
# Creating an object called iris with iris data:
iris = load_iris()
#print(iris)
# Creating a data frame with four feature variables:
df = pd.DataFrame (iris.data, columns=iris.feature_names)
# Viewing the top 5 rows:
df.head()

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
0                5.1               3.5                1.4               0.2
1                4.9               3.0                1.4               0.2
2                4.7               3.2                1.3               0.2
3                4.6               3.1                1.5               0.2
4                5.0               3.6                1.4               0.2

In [3]:
# Adding a new column for the species name:
df['Species'] = pd.Categorical.from_codes(iris.target, iris.target_names)
# Viewing the top 5 rows:
df.head()

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)  \
0                5.1               3.5                1.4               0.2   
1                4.9               3.0                1.4               0.2   
2                4.7               3.2                1.3               0.2   
3                4.6               3.1                1.5               0.2   
4                5.0               3.6                1.4               0.2   

  Species  
0  setosa  
1  setosa  
2  setosa  
3  setosa  
4  setosa

OR!! 

In [4]:
data = pd.read_csv('iris.csv')
data.head()

Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm      Species
0   1            5.1           3.5            1.4           0.2  Iris-setosa
1   2            4.9           3.0            1.4           0.2  Iris-setosa
2   3            4.7           3.2            1.3           0.2  Iris-setosa
3   4            4.6           3.1            1.5           0.2  Iris-setosa
4   5            5.0           3.6            1.4           0.2  Iris-setosa

In [5]:
# Creating test and train data:
df['is_train'] = np.random.uniform(0, 1, len(df)) <= 0.75
# View top 5 rows:
df.head()

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)  \
0                5.1               3.5                1.4               0.2   
1                4.9               3.0                1.4               0.2   
2                4.7               3.2                1.3               0.2   
3                4.6               3.1                1.5               0.2   
4                5.0               3.6                1.4               0.2   

  Species  is_train  
0  setosa      True  
1  setosa      True  
2  setosa      True  
3  setosa      True  
4  setosa      True

In [6]:
# Creating dataframes with test rows and training rows:
train, test = df[df['is_train'] == True], df[df['is_train'] == False]
# Show the number of observations for the test and traing dataframes:
print('Number of observations in training data:',len(train))
print('Number of observations in test data:',len(test)) 


Number of observations in training data: 118
Number of observations in test data: 32


In [7]:
# Create a list of the features and column names:
features = df.columns[:4]
# View features:
features

Index(['sepal length (cm)', 'sepal width (cm)', 'petal length (cm)',
       'petal width (cm)'],
      dtype='object')

In [8]:
# Converting each species name into digits:
y = pd.factorize(train['Species'])[0]
# Viewing target:
y

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2], dtype=int64)

In [10]:
# Creating a Random FOrest Classifier:
clf = RandomForestClassifier(n_jobs=2, random_state=0) 
# Training the Classifier:
clf.fit(train[features], y)

RandomForestClassifier(n_jobs=2, random_state=0)


In [90]:
# Applying the trained classifier to the test:
print(test[features].head())
clf.predict(test[features])

    sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
7                 5.0               3.4                1.5               0.2
8                 4.4               2.9                1.4               0.2
10                5.4               3.7                1.5               0.2
13                4.3               3.0                1.1               0.1
17                5.1               3.5                1.4               0.3


array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 2, 2, 1, 1, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2], dtype=int64)

In [91]:
# Viewing the predicted probablities of the first 10 observations:
clf.predict_proba(test[features])[0:10]


array([[1.  , 0.  , 0.  ],
       [1.  , 0.  , 0.  ],
       [1.  , 0.  , 0.  ],
       [1.  , 0.  , 0.  ],
       [1.  , 0.  , 0.  ],
       [0.95, 0.05, 0.  ],
       [1.  , 0.  , 0.  ],
       [0.99, 0.01, 0.  ],
       [1.  , 0.  , 0.  ],
       [1.  , 0.  , 0.  ]])

In [92]:
# mapping the names for the plants for each predicted plant class:
preds = iris.target_names[clf.predict(test[features])]
# View the PREDICTED species for the first 5 observations:
preds[0:5]

array(['setosa', 'setosa', 'setosa', 'setosa', 'setosa'], dtype='<U10')

In [93]:
# Viewing the ACTUAL species for the first five observations:
test['Species'].head()

7     setosa
8     setosa
10    setosa
13    setosa
17    setosa
Name: Species, dtype: category
Categories (3, object): ['setosa', 'versicolor', 'virginica']

In [94]:
# Creating a confusion matrix:
pd.crosstab(test['Species'], preds, rownames=['Actual Species'], colnames=['Predicted Species'])

Predicted Species  setosa  versicolor  virginica
Actual Species                                  
setosa                 13           0          0
versicolor              0           5          2
virginica               0           0         12

In [95]:
preds = iris.target_names[clf.predict([[5.0, 3.6, 1.4, 2.0], [5.0, 3.6, 1.4, 2.0]])]
preds

c:\Users\M.K.M\AppData\Local\Programs\Python\Python39\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but RandomForestClassifier was fitted with feature names
  warnings.warn(


array(['setosa', 'setosa'], dtype='<U10')